email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "mggummow@gmail.com"
  password: "innr syza kruq tnwz"
  imap_server: "imap.gmail.com"

database:
  mongodb_uri: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@vds.dannydemosi.com:27017"
  database_name: "family_stories"
