email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-specific-password"
  imap_server: "imap.gmail.com"

database:
  mongodb_uri: "mongodb://localhost:27017"
  database_name: "family_stories"
